version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    container_name: springboot-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/music_album_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    container_name: vue-frontend
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:17.4
    container_name: postgres-db
    environment:
      POSTGRES_DB: music_album_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgres/data
    ports:
      - "5433:5432"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
